Adding instrcutions for SageMaker RL
Unity-Technologies/ml-agents pull request #4806
Opened 2020-12-28 10:44 UTC by yoheigon

### Proposed change(s)

Describe the changes made in this PR.

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [x] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [x] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### Other comments

2020-12-28 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Unity-Technologies/ml-agents?pullRequest=4806) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Unity-Technologies/ml-agents?pullRequest=4806) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Unity-Technologies/ml-agents?pullRequest=4806) it.</sub>

2021-01-08 02:01 UTC, yoheigon commented
@chriselion 
Could you review this PR?

2021-01-08 17:28 UTC, chriselion commented
Sorry, we need to discuss this internally more, and some of the relevant people are on vacation this week.

2021-01-11 23:21 UTC, unityjeffrey commented
hi @yoheigon hope you are doing well.  Apologies for the late reply.  Thank you for writing this up, this would be beneficial for our users who are wanting to use ML-Agents with Sagemaker.  I was wondering if this document would be better suited to be hosted on the Amazon site (and we can link from here).  We have gotten away from providing documentation and support to run ml-agents on cloud providers as there is a support burden and knowledge gap on our end.

if you think it makes sense to include it in the core ml-agents documentation, then I would suggest the following changes:

1.  In the title, please include a note that this is only tested for a specific version of ML-Agents.  This will prevent users from trying to follow these instructions on a later version of ML-Agents.
2.  Please also include a note to indicate that this isn't generally supported by the ML-Agents team, but that it's included in case it may be helpful
3.  If folks have any questions or additional followups, is there an Amazon POC or support email address that can be added?  We end up getting questions in the forums or issues and would be good to be able to route them to someone at Amazon.

For 1-2, the Azure doc is a good example.  https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Microsoft-Azure.md

Let me know on my note above, I'll also make some comments in the documentation itself.

Thanks!

Jeff

2021-01-11 23:43 UTC, unityjeffrey requested changes

2021-01-11 23:43 UTC, unityjeffrey commented on docs/Training-on-Amazon-SageMaker-RL.md
> +## Training on Amazon SageMaker RL
please use #

2021-01-11 23:43 UTC, unityjeffrey commented on docs/Training-on-Amazon-SageMaker-RL.md
> +SageMaker is a fully managed service that enables fast model development. It provides many built-in features to assist you with training, tuning, debugging, and model deployment. SageMaker RL builds
this section is a bit too much marketing - can you instead create a link to Sagemaker RL instead?  The architecture diagram below is helpful though.

2021-01-11 23:43 UTC, unityjeffrey commented on docs/Training-on-Amazon-SageMaker-RL.md
> +In this section, we walk you through the steps to set up your environment to launch SageMaker RL training jobs.
"we **will** walk"

2021-01-11 23:43 UTC, unityjeffrey commented on docs/Training-on-Amazon-SageMaker-RL.md
> +To get started, we import the needed Python libraries and set up environments for permissions and configurations. The following code contains the steps to set up an [Amazon Simple Storage Service](ht
"we **first need to** import"

2021-01-11 23:43 UTC, unityjeffrey commented on docs/Training-on-Amazon-SageMaker-RL.md
> +In this section, we walk you through the steps to train, evaluate, and deploy models.
"we **will** walk"

2021-01-11 23:43 UTC, unityjeffrey commented on docs/Training-on-Amazon-SageMaker-RL.md
> +Out of five episodes, the average episode reward is 0.92 with the maximum reward of 0.93 and minimum reward of 0.89, suggesting the trained model indeed performs well.
this seems out of place.  I would put a qualifier like "For example, out of the five episodes..."

2021-01-11 23:43 UTC, unityjeffrey commented on docs/Training-on-Amazon-SageMaker-RL.md
> +1. In the Unity Editor, load a project containing an ML-Agents environment (you can use one of the example environments if you have not created your own but please make sure your environment only con
I would make a note that this example uses the Basic environment and link it (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Examples.md#basic)

2021-01-11 23:43 UTC, unityjeffrey commented on docs/Training-on-Amazon-SageMaker-RL.md
> +In our code example, we invoke a predefined Unity environment called Basic, but you can experiment with other [pre-built Unity environments](https://github.com/Unity-Technologies/ml-agents/blob/maste
I would put this note around single-agent environment as a separate disclaimer or move it up in the document.

2021-04-07 16:10 UTC, closed without merging