Some edits to the documentation
Unity-Technologies/ml-agents pull request #5369
Opened 2021-05-14 22:11 UTC by vincentpierre

### Proposed change(s)

Some comments are not picked up correctly by the markdown generator. I modified these comments for correctness.

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/main/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Migrating.md) (if applicable)

### Other comments

2021-05-17 15:29 UTC, miguelalonsojr requested changes

2021-05-17 15:29 UTC, miguelalonsojr commented on ml-agents-envs/mlagents_envs/base_env.py
> +    Observation contains goal information for current task
Add a period for consistency.

2021-05-17 16:12 UTC, vincentpierre commented on ml-agents-envs/mlagents_envs/base_env.py
> +    Observation contains goal information for current task
```suggestion
    Observation contains goal information for current task.
```

2021-05-18 12:31 UTC, miguelalonsojr approved these changes

2021-05-18 12:31 UTC, merged