Add tips in docs
Unity-Technologies/ml-agents pull request #5566
Opened 2021-10-05 05:23 UTC by DeathVenom54

### Proposed change(s)

I updated a code block and added little tips to explain things better, ones I wish were included when I was first learning from the docs.

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [x] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [x] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/main/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Migrating.md) (if applicable)

### Other comments

2021-10-05 05:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Unity-Technologies/ml-agents?pullRequest=5566) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Unity-Technologies/ml-agents?pullRequest=5566) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Unity-Technologies/ml-agents?pullRequest=5566) it.</sub>

2022-01-19 00:21 UTC, miguelalonsojr commented
@maryamhonari or @jrupert-unity can you have a look at this PR? Seems reasonable since it's a doc update.

2022-01-19 07:56 UTC, jrupert-unity requested changes
Changes make some good improvements, but need work.

I would remove the change around line 234.
I'd remove line 270 and change 272&273 to use actionBuffers.ContinuousActions[].  Same with 319&320.  
Line 264 should say ContinuousActions[] or actionBuffers.ContinuousActions[]. 
Line 443 should be "Make sure the behavior name in the 'Behavior Parameters' component matches the one in the config file."  to fix spelling and punctuation.

2022-01-19 09:42 UTC, DeathVenom54 commented
Hey I am very new to OS contributions. I cannot see any options to edit the code in my pull request.

2022-01-19 21:50 UTC, jrupert-unity commented
I think if you push more changes to the file it will update.  Alternatively if Miguel approves we can accept this pull request and I can update with my changes after that.

2022-01-20 02:23 UTC, DeathVenom54 commented
Alright, I'll do that

2026-06-11 14:14 UTC, montplaisir commented
Thanks for improving our docs! Your PR will be integrated as part of #6298.

Note that the documentation in the `docs` directory is no longer maintained. The updates will be done in directory [com.unity.ml-agents/Documentation~/](https://github.com/Unity-Technologies/ml-agents/tree/develop/com.unity.ml-agents/Documentation~).

2026-06-11 14:14 UTC, closed without merging