Package changes to support deterministic inference
Unity-Technologies/ml-agents pull request #5599
Opened 2021-10-29 18:08 UTC by mahon94

### Proposed change(s)

Describe the changes made in this PR.

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/main/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Migrating.md) (if applicable)

### Other comments

2021-11-02 17:32 UTC, miguelalonsojr requested changes
High level review before digging into the code:

1. You mentioned this is an editor only option. Can we make this a runtime option as well? My thinking here is that folks may want to package up the policy and set it to deterministic mode and ship it that way.
2. Let's be consistent between the python and Unity side. The default is assumed to be Stochastic, so you must add a "deterministic" flag to either the CLI or config. Let's do the same in Behavior Parameters, i.e. the checkbox should be labeled "Deterministic Policy" and have it unchecked. by default.

2021-11-04 16:28 UTC, mahon94 commented
1.  The flag only works within unity editor or unity standalone after build. If it's used from python `mlagents-learn`, `--deterministic` should be used.
2.  2.Done, reverted the flag to deterministic inference.

Thanks

2021-11-10 14:08 UTC, miguelalonsojr requested changes

2021-11-10 14:08 UTC, miguelalonsojr commented on com.unity.ml-agents/Tests/Editor/Inference/ModelRunnerTest.cs
> +            Assert.IsFalse(Enumerable.SequenceEqual(stochAction1, stochAction2, new FloatThresholdComparer(0.001f)));
I think it would be a good idea to refactor this test into two tests, one for deterministic actions and one for stochastic actions.

2021-11-16 22:25 UTC, cmard approved these changes

2021-11-17 21:10 UTC, miguelalonsojr approved these changes
LGTM.

2021-11-18 15:39 UTC, merged